### ISSUE TITLE
steamGameControl crash due to API call limit?

### ISSUE THREAD

**Issue by mhvuze** [vishwenga/Steam-Boost#1]
Hi,

![unbenannt](https://user-images.githubusercontent.com/4907001/27475347-33aa4118-5805-11e7-9f60-f8608e8a62d1.jpg)

E: After further investigation, it might not be specific to this AppID. Hm. Here is my json: http://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/?key=006C1D814005AF1CAE4B670EE4B38979&steamid=76561198081075389&l=english&json

E2: I have found info via google that points to the error being related to API call limits. Makes sense, my account has quite a bunch of licenses associated to it.

E3: I used my own API key but it still didn't work :/ Skipping the individual game requests and using a temporary name for the Game() worked but eh :p Atleast I can idle the few games I want now after figuring out the App ID :)

**Comment by vishwenga** [comment]
try making it sleep/delay before line 50.
check how many games it collect before it run into that restriction and put like 5min sleep

**Comment by mhvuze** [comment]
What I eventually did was to collect the game name from the steam store page via scraping and in case of a removed app, fall back to the API. Worked out fine even though it took quite a while :)

**Comment by 00000vish** [comment]
I updated it, let me know if that got it working or not.
