### ISSUE TITLE
Sorry for opening an issue, you didn't have any contact info.

### ISSUE THREAD

**Issue by daniel-barbu** [vishwenga/Steam-Boost#2]
Hello,

Do you know why you have to set your privacy settings to public? I have a similar idling tool for Steam games and I was strugluing to get card drops until I stumbled upon your repo. Does it have to do with SteamAchievementManager?

Thank you in advance, 
Daniel.

**Comment by 00000vish** [comment]
No, from my understanding steam only drops cards after 2 hours of game play and randomly when game is closed.
